// <auto-generated />
using System;
using IaAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IaAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArbitrageDbContext))]
    [Migration("20260608030628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("IaAgent.Domain.Entities.ArbitrageCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChineseProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CifValueUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustomsDutyUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossMarginPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossProfitUsd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProfitable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IvaUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MercadoLibreFeeUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetMarginPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfitUsd")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Roi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingToChileCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetSellingPriceClp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetSellingPriceUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsdToClpRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsProfitable");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.ToTable("ArbitrageCalculations");
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.ChineseProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedShippingDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinOrderQuantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupplierRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId", "ExternalProductId", "SourcePlatform")
                        .IsUnique();

                    b.ToTable("ChineseProducts");
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.MarketOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveListingsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentChileanPriceClp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DemandScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoLibreProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldLast30Days")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemandScore");

                    b.HasIndex("MercadoLibreProductId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.MercadoLibreListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoLibreListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceClp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSales")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MercadoLibreListingId");

                    b.HasIndex("Status");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChineseProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderPlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("Status");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.ArbitrageCalculation", b =>
                {
                    b.HasOne("IaAgent.Domain.Entities.MarketOpportunity", null)
                        .WithOne("Calculation")
                        .HasForeignKey("IaAgent.Domain.Entities.ArbitrageCalculation", "OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.ChineseProduct", b =>
                {
                    b.HasOne("IaAgent.Domain.Entities.MarketOpportunity", null)
                        .WithMany("ChineseProducts")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IaAgent.Domain.Entities.MarketOpportunity", b =>
                {
                    b.Navigation("Calculation");

                    b.Navigation("ChineseProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
